name = "Athena 3.0.0"
host = "0.0.0.0"
port = 7788
players = 512
announce = false
gamemode = "Roleplay"
website = "athenaframework.com"
language = "en"
description = "A Roleplay Framework for alt:V"
debug = true
streamingDistance = 400
migrationDistance = 150
timeout = 1
announceRetryErrorDelay = 10000
announceRetryErrorAttempts = 50
modules = [js-module]
resources = [webserver","core]
tags = [athena","framework","version","3]
useEarlyAuth = false
useCdn = false

[voice]
bitrate = 64000

[js-module]
source-maps = true
heap-profiler = true
profiler = true
global-fetch = true
global-webcrypto = true
network-imports = true
extra-cli-args = [--inspect=127.0.0.1:9229","--max-old-space-size=8192]

[js-module.inspector]
host = "127.0.0.1"
port = 9229

[config.js-module-v2]
compatabilityEnabled = true

